### ISSUE TITLE
Override scientific notation

### ISSUE THREAD

**Issue by davidfgeorge** [vonjd/OneR#12]
Hi. I am experimenting with OneR, which I believe will be very helpful for discovering and implementing domain-specific heuristics. However, I would really like to somehow override the scientific notation as is printed. Use of  options(scipen = 999) for example has no effect. Thank you.

**Comment by vonjd** [comment]
Could you give a reproducible example of what you get and what you would like to get? Thank you

**Comment by vonjd** [comment]
As an aside: to get some inspiration for possible use cases: [https://blog.ephorie.de/category/oner](https://blog.ephorie.de/category/oner)

**Comment by davidfgeorge** [comment]
Thank you for the references. I try to read most of your R-bloggers posts, which I find interesting and usually entertaining. Thank you.
The values of model$rules for an example element is:
$`(5.64e+04,7.1e+04]`
[1] "high"
I can programatically isolate, extract and format the returned range to: 56,400 , 71,000
for output display purposes, but wondered if I can override internal scientific notion?
Thank you.

**Comment by vonjd** [comment]
No, it is not possible to override it at the moment (like with the `dig.lab` argument in the `cut()` function). Would this be a useful feature for future versions of the OneR package?

**Comment by davidfgeorge** [comment]
Hi. Yes, but that is only my personal opinion. As mentioned, I can programmatically reformat for output presentation purposes. Thank you.
