### ISSUE TITLE
Save output of verbose=T to an object

### ISSUE THREAD

**Issue by duplisea** [vonjd/OneR#13]
This is more a call for help than an issue:

When I run the function OneR with the verbose=T option, I get nice output to the console with the name of the attribute and the Accuracy (ranked from best to worst). I would like to save that output (the M matrix), preferably as part of the list of the fitted object. I thought it would be easy just to make my own version of the OneR function including the M matrix in the output list:
```
  output <- c(call = call, target = target, feature = feature, 
    rules = list(majority), correct_instances = max(perf), 
    total_instances = nrow(data), cont_table = list(cont_table), M=M)
```

but it does not work and I get this error:

> Error in sapply(tables, nerrors) : object 'nerrors' not found
> In addition: Warning message:
> In OneR(dat.oner, verbose = T) :
>  Error in sapply(tables, nerrors) : object 'nerrors' not found

I then tried adding the line M.out <<- M to write it directly to the workspace after the verbose section but I get the same error.

My ultimate goal is to get an object where I can select say the top 5 ranked attributes for further analysis (in a matrix of up to say 200 attributes).

I suspect that this is really a misunderstanding of how UseMethod works in R than anything specific about OneR.

Can you tell me how to get the M matrix saved as an object in my workspace?

**Comment by vonjd** [comment]
One possibility would be to use `capture.output`:

```
data.frame(capture.output(model <- OneR(iris, verbose = TRUE)))
##    capture.output.model....OneR.iris..verbose...TRUE..
## 1                                                     
## 2                                Attribute    Accuracy
## 3                            1 * Petal.Width  94%     
## 4                            2   Petal.Length 90%     
## 5                            3   Sepal.Length 64%     
## 6                            4   Sepal.Width  54.67%  
## 7                                                  ---
## 8                     Chosen attribute due to accuracy
## 9                 and ties method (if applicable): '*'
## 10
```

But because the verbose output wasn't made for further analysis you would have to do a little bit of postprocessing (splitting and stuff).
