### ISSUE TITLE
Error when installing in R 3.4.0

### ISSUE THREAD

**Issue by heidi2780** [vonjd/OneR#4]
When installing OneR to R 3.4.0, I got this error as following:

> install.packages("OneR")
Warning in install.packages :
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/OneR_2.2.zip'
Content type 'application/zip' length 85146 bytes (83 KB)
downloaded 83 KB
package ‘OneR’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Users\heidi\Documents\R\R-3.4.0\library\file1ed0f62604d\OneR’ to ‘C:\Users\heidi\Documents\R\R-3.4.0\library\OneR’
The downloaded binary packages are in
	C:\Users\heidi\AppData\Local\Temp\RtmpSCNasD\downloaded_packages

**Comment by vonjd** [comment]
@heidi2780 Thank you for reporting this issue. Are you using R Studio version 1.0.143? Because this is a known issue there: https://support.rstudio.com/hc/en-us/community/posts/115006223707-New-version-of-RStudio-gives-warning-on-package-install

**Comment by heidi2780** [comment]
Thank you for your reply. Yes, I am using RStudio 1.0.143. While when I installed it in RGui(64-bit) 3.4, the following error appeared:

> utils:::menuInstallPkgs()
--- Please select a CRAN mirror for use in this session ---
trying URL 'http://cran.utstat.utoronto.ca/bin/windows/contrib/3.4/OneR_2.2.zip'
Content type 'application/zip' length 85146 bytes (83 KB)
downloaded 83 KB
package ‘OneR’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\heidi\Documents\R\R-3.4.0\library\file153c7bb92fad\OneR’ to ‘C:\Users\heidi\Documents\R\R-3.4.0\library\OneR’
The downloaded binary packages are in
        C:\Users\heidi\AppData\Local\Temp\Rtmpodjgcv\downloaded_packages

> library(OneR)
Error in library(OneR) : there is no package called ‘OneR’

**Comment by vonjd** [comment]
@heidi2780 Ok, pls try the following:
1. Close RStudio and start base R
2. Install package there, either by install.packages("OneR") or by menu "Packages/Install package(s)"
3. Close base R and start RStudio again

Please try "library(OneR)" and "OneR(iris)" to see if everything works ok.

Pls. tell me whether this works - Thank you

**Comment by heidi2780** [comment]
@vonjd  Thank you. It works now. :)

**Comment by vonjd** [comment]
@heidi2780 I am glad that everything works alright now. Sorry for the inconvenience but it is really not my fault. I hope that Microsoft will fix this error in the next update of RStudio. 

If you have any other questions pls. feel free to reach out.

Happy analyzing with the OneR package!

**Comment by heidi2780** [comment]
@vonjd Thank you so much for your time. I will start to explore OneR.
