### ISSUE TITLE
OneR is not available for R version 3.2.2

### ISSUE THREAD

**Issue by bhulet** [vonjd/OneR#5]
Hi, I'm trying to install from MRAN on an instance of R Server, however I am getting this standard version error noted in the subject. 

I've tried specifying install from CRAN and from your github repository without success. Do you have any additional ideas? I do not think I am am able to update the version of R.

Thanks,

Ben

Edit: the error is occurring on R Server 8.0.

**Comment by vonjd** [comment]
Thank you for reaching out and letting me know. I am sorry that you encounter these installation problems.

This is really strange. I had this version myself and everything worked alright. There are already more than ten thousand installations of OneR from CRAN and Github, so I suspect that there might be something wrong with your configuration.

On top of that OneR is one of the few packages that is not dependent on any other packages, additionally it doesn't need compilation and is succesfully tested on all possible OS versions without any error: https://cran.r-project.org/web/checks/check_results_OneR.html

Does this installation problem only occur for OneR or also for other packages?

Perhaps this question (and respective answers) on SE might be helpful: https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa

Thank you for using the OneR package

**Comment by vonjd** [comment]
Because I haven't heard back from you I suppose the issue is solved.

Thank you for using the OneR package
