### ISSUE TITLE
How does optbin() function optimize the cut points?

### ISSUE THREAD

**Issue by HMais** [vonjd/OneR#7]
Thanks for the great package!
I ‘m using your discretization function optbin() in a comparative analysis of different discretization methods. 
I read the documentation about this function (p. 9 - 11), but I remain confused, especially about the "logreg" and the "naive" methods…
Could you please provide more details about the three discretization methods available through the optbin().
Thanks!

**Comment by vonjd** [comment]
What exactly is it, that you don't understand?
I think best would be to have a look at the source code for all the details: [https://github.com/vonjd/OneR/blob/master/R/OneR_internal.R](https://github.com/vonjd/OneR/blob/master/R/OneR_internal.R)

The important function here is `optcut`: the method `naive` is done directly there, the method `logreg` can be found in the function `logreg_midpoint`.

The source code is documented, if you have any specific questions please do not hesitate to reach out!

**Comment by HMais** [comment]
Thanks very much for your prompt reply. The code documentation answers my questions.

**Comment by vonjd** [comment]
Could you perhaps post a link here when your analysis is ready? That would be great!
